# Generated by Django 2.1 on 2019-05-13 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevicesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
                ('device_ip', models.CharField(max_length=40)),
                ('device_model', models.CharField(max_length=100)),
                ('device_sn', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SitesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('site_location', models.CharField(max_length=250)),
                ('site_poc_name', models.CharField(max_length=100)),
                ('site_poc_number', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='devicesmodel',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='main_app.SitesModel'),
        ),
    ]
