# Generated by Django 2.1 on 2019-05-13 19:50

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DevicesModel',
            new_name='Devices',
        ),
        migrations.RenameModel(
            old_name='SitesModel',
            new_name='Sites',
        ),
    ]
