# Generated by Django 2.1 on 2019-05-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190513_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='site_address',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
