# Generated by Django 2.1 on 2019-05-14 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_deviceconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceconfig',
            name='id',
        ),
        migrations.AlterField(
            model_name='deviceconfig',
            name='device_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='config', serialize=False, to='main_app.Devices'),
        ),
    ]
