# Generated by Django 2.1 on 2019-05-15 21:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20190514_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceconfig',
            name='last_modify',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
