# Generated by Django 2.1 on 2019-05-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_deviceconfig_last_modify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceconfig',
            name='last_modify',
            field=models.DateTimeField(null=True),
        ),
    ]
