# Generated by Django 2.1 on 2019-05-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20190515_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='device_ip',
            field=models.GenericIPAddressField(),
        ),
    ]
