# Generated by Django 2.1 on 2019-05-22 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20190522_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceDetail',
            fields=[
                ('device_model', models.CharField(max_length=100)),
                ('device_sn', models.CharField(max_length=250)),
                ('device_config', models.TextField(null=True)),
                ('device_script', models.TextField(null=True)),
                ('last_modify', models.DateTimeField(null=True)),
                ('device_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='config', serialize=False, to='main_app.Devices')),
            ],
        ),
        migrations.RemoveField(
            model_name='deviceconfig',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='devices',
            name='device_model',
        ),
        migrations.RemoveField(
            model_name='devices',
            name='device_sn',
        ),
        migrations.AddField(
            model_name='devices',
            name='vendor',
            field=models.CharField(choices=[('C', 'Cisco'), ('J', 'Juniper'), ('A', 'Arista')], default=('C', 'Cisco'), max_length=10),
        ),
        migrations.DeleteModel(
            name='DeviceConfig',
        ),
    ]
