# Generated by Django 2.1 on 2019-05-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20190522_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedetail',
            name='device_model',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='devicedetail',
            name='device_sn',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
