# Generated by Django 2.1 on 2019-05-24 21:59

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20190522_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedetail',
            name='config_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devicedetail',
            name='last_modify',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 5, 24, 21, 58, 24, 890090, tzinfo=utc)),
        ),
    ]
