# Generated by Django 2.1 on 2019-05-24 22:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20190524_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedetail',
            name='config_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicedetail',
            name='last_modify',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2019, 5, 24, 22, 16, 55, 217059, tzinfo=utc)),
        ),
    ]
