# Generated by Django 2.1 on 2019-05-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20190524_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedetail',
            name='config_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='devicedetail',
            name='last_modify',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
