# Generated by Django 2.1 on 2019-05-24 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0014_auto_20190524_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedetail',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='createdby', to=settings.AUTH_USER_MODEL),
        ),
    ]
