# Generated by Django 2.1 on 2019-06-03 03:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_devicedetail_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
