# Generated by Django 2.1 on 2019-06-03 18:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_sites_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
