# Generated by Django 2.1 on 2019-06-04 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_devices_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedetail',
            name='created_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='createdby', to=settings.AUTH_USER_MODEL),
        ),
    ]
