# Generated by Django 2.1 on 2019-06-04 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0020_auto_20190604_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedetail',
            name='modified_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modifiedby', to=settings.AUTH_USER_MODEL),
        ),
    ]
