# Generated by Django 2.1 on 2019-06-04 23:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_devicedetail_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedetail',
            name='last_modify',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
