# Generated by Django 2.1 on 2019-06-05 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_auto_20190605_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicedetail',
            name='device_model',
        ),
        migrations.RemoveField(
            model_name='devicedetail',
            name='device_sn',
        ),
        migrations.AddField(
            model_name='devices',
            name='device_model',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='devices',
            name='device_sn',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
