# Generated by Django 2.1 on 2019-06-05 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_auto_20190605_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='device_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='devices',
            name='device_sn',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
