# Generated by Django 2.1 on 2019-06-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_auto_20190605_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='device_type',
            field=models.CharField(choices=[('R', 'Router'), ('S', 'Switch'), ('F', 'Firewall')], default=('R', 'Router'), max_length=10),
        ),
    ]
