# Generated by Django 2.1 on 2019-06-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_devices_operating_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedetail',
            name='interfaces',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='devicedetail',
            name='vlans',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
