# Generated by Django 2.1 on 2019-06-12 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0029_auto_20190611_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceinterfaces',
            name='interfaces',
            field=models.TextField(blank=True, null=True),
        ),
    ]
