# Generated by Django 2.1 on 2019-06-13 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0032_auto_20190611_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicevlans',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vlans', to='main_app.Devices'),
        ),
    ]
