# Generated by Django 2.1 on 2019-06-13 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0033_auto_20190613_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceinterfaces',
            name='interfaces',
        ),
        migrations.AddField(
            model_name='deviceinterfaces',
            name='interface_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='deviceinterfaces',
            name='interfaces_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='deviceinterfaces',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_interface', to='main_app.Devices'),
        ),
    ]
