# Generated by Django 2.1 on 2019-06-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0036_devices_software_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='device_password',
            field=models.CharField(default='no_password', max_length=250),
        ),
        migrations.AddField(
            model_name='devices',
            name='device_username',
            field=models.CharField(default='user', max_length=100),
        ),
    ]
