# Generated by Django 2.1 on 2019-06-20 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0037_auto_20190619_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='device_password',
            field=models.CharField(max_length=250),
        ),
    ]
